:broom:[#15]Expense entity의 attribute 4개 추가
DeveloperAcademy-POSTECH/MacC-Team11-UMM pull request #16
Opened 2023-10-10 14:50 UTC by unboxing96

## 👀 이슈
- #15

## 💡 작업 내용
- Expense entity의 attribute 4개 추가

## 📱스크린샷

### FigJam
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/102353544/1941b449-7fb6-4113-8d17-0297e7e9c0d3)

### xcode 내부 .xcdatamodeld
<img width="1163" alt="스크린샷 2023-10-10 오후 11 43 33" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/102353544/4291dd0c-797c-4179-8667-75fc7cc0b4c6">

## 🚨 참고 사항
- 추가한 attribute: payDate, currency, exchangeRate, location
- GPS 위치 정보 타입은 위도﹒경도 값만 받아오는 CLLocationCoordinate2D 타입이 있다고 함. (더 많은 정보가 있는 CLLocation을 선택할지 고민)
- currency(화폐 종류)는 enum으로 사용하기 위해, 컨벤션에 맞춰 Int64 타입으로 설정 + 값 초기화(-1)

## (Optional) 🤔 고민한 점
- location(GPS 위치 정보)만 받아서 계산하는 것이 맞는지, 혹은 "국가"를 따로 attribute로 저장하는 것이 맞는지?
- Core Data에서 enum을 저장하는 방법: https://www.swiftdevjournal.com/storing-a-swift-enum-in-core-data/

2023-10-11 01:15 UTC, GYURI-PARK requested changes
수고했어욥 🦦

2023-10-11 01:15 UTC, GYURI-PARK commented on UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
> +        <attribute name="location" optional="YES" attributeType="Transformable" customClassName="CLLocationCoordinate2D"/>
location 타입 에러 해결 후 다시 PR 날려주세요~~~

2023-10-11 02:59 UTC, oliver-or-not requested changes
GYURI-PARK 말에 동의해요~

2023-10-12 01:00 UTC, GYURI-PARK approved these changes
LGTM !

2023-10-12 01:00 UTC, oliver-or-not approved these changes
잘 수정했군요!

2023-10-12 01:00 UTC, oliver-or-not commented on UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
> +        <attribute name="location" optional="YES" attributeType="String"/>
입력 예시: "대한민국 경상북도 포항시 효자동"이군요

2023-10-12 01:01 UTC, merged