Feat/55 ExpenseView들의 기능 구현
DeveloperAcademy-POSTECH/MacC-Team11-UMM pull request #62
Opened 2023-10-17 15:38 UTC by unboxing96

## 👀 이슈
- #55 

## 💡 작업 내용
- AllExpenseView, AllExpenseDetailView 기능 구현

## 📱스크린샷
<img width="335" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/102353544/8f9f917b-106d-432a-98f3-dd2919d03a66">
* AllExpenseView의 Travel과 Country로 필터링 되고 있는 화면

## 🚨 참고 사항
- dummyRecordViewModel과 ExpenseViewModel 합칠 예정
- 현재 Picker로 되어있는 것을, @oliver-or-not의 모달로 교체 예정
- Picker의 초기값이 제대로 view를 그려주지 않는 문제 해결 예정

## (Optional) 🤔 고민한 점
- ViewModel -> 부모View -> (Navigation) -> 자식View 흐름대로 데이터를 이용하는 부분에서 고민을 많이 했습니다.
- 선택한 방법은 ViewModel에서 @Published 변수로 아래 View에서 사용할 것들을 선언해 두고, 아래 View에서 Published 변수를 건드려서 뷰를 그려주는 방식입니다.
- Navigation을 통해 데이터를 전달할 때는 viewModel을 직접 @Binding 변수로 전달하려 했으나, 실패했습니다.
- 부모 View에서는 ViewModel에 저장된 @Published 변수를 직접 이용하고, 자식 View로 넘겨줄 때 @Binding 변수를 하나씩 초기화 해주었습니다.

2023-10-17 16:54 UTC, oliver-or-not commented on UMM/Dummy/TempSave.swift
> +    let dummyExpensePaymentMethod = Int.random(in: 0...2)
현재의 PaymentMethod 이뉴머레이션에서는 -1, 0, 1이 각각 .unknown, .card, .cash입니다. 2를 넣어주면 문제가 될 것 같아요!

2023-10-17 16:56 UTC, oliver-or-not commented on UMM/Dummy/TempSave.swift
> +    let dummyExpensePaymentMethod = Int.random(in: 0...2)
(그런데 .all은 어떤 경우에 사용하나요?)

2023-10-17 17:05 UTC, GYURI-PARK approved these changes
페페 오늘도 수고했어욥 🦦

2023-10-17 17:05 UTC, GYURI-PARK commented on UMM/View/Expense/AllExpenseView.swift
> +        NavigationStack {
MainView에 NavigationStack이 걸려있는데 여기서 한번더 걸어준 이유가 있나요??

2023-10-17 17:08 UTC, oliver-or-not commented on UMM/View/Expense/AllExpenseDetailView.swift
> +    private func drawExpensesDetail(expenses: [Expense]) -> some View {
이 함수로 그린 뷰는 입력값 expesnes가 변화해도 갱신이 안 되지 않나요?

2023-10-17 17:10 UTC, oliver-or-not commented on UMM/View/Expense/AllExpenseView.swift
> +                    expenseViewModel.filteredExpenses = getFilteredExpenses(selectedCountry: expenseViewModel.selectedCountry)
ExpenseViewModel 안에서 selectedCountry에 대한 옵저버로 필터를 자동 실행하는 방식도 고려해볼 수 있지 않을까요? 자동으로 필터를 하면 코드의 안정성이 올라갈 것 같다는 의견입니다.

2023-10-17 17:13 UTC, oliver-or-not commented on UMM/View/Expense/AllExpenseView.swift
> +                    expenseViewModel.filteredExpenses = getFilteredExpenses(selectedCountry: expenseViewModel.selectedCountry)
다른 코드도 읽어보니 바인딩 변수를 이용해서 필터하기 위한 노력이었군요

2023-10-17 17:14 UTC, oliver-or-not commented on UMM/View/Expense/AllExpenseView.swift
> +    private func getFilteredExpenses(selectedCountry: Int64) -> [Expense] {
코어 데이터 + MVVM + 네비게이션 링크의 조합 때문에 뷰모델이 뷰모델의 역할을 제대로 하지 못해서 뷰에서 복잡한 작업을 하게 되었네요.

2023-10-17 17:15 UTC, oliver-or-not commented on UMM/View/MainView.swift
> +                    DummyRecordView()
;;

2023-10-17 17:15 UTC, oliver-or-not approved these changes
수고했어요 페페!

2023-10-17 17:16 UTC, oliver-or-not reviewed
.

2023-10-18 00:26 UTC, unboxing96 commented on UMM/Dummy/TempSave.swift
> +    let dummyExpensePaymentMethod = Int.random(in: 0...2)
.all을 취소하도록 하겠습니다.

2023-10-18 01:06 UTC, GYURI-PARK requested changes

2023-10-18 01:06 UTC, GYURI-PARK commented on UMM/View/Expense/AllExpenseDetailView.swift
> +            .onChange(of: selectedPaymentMethod) { newValue in
'onChange(of:perform:)' was deprecated in iOS 17.0: Use `onChange` with a two or zero parameter action closure instead. 저희 타겟을 17로 맞출려면 이부분 수정해야할꺼 같아요 !!!

2023-10-19 00:24 UTC, GYURI-PARK approved these changes
LGTM :!

2023-10-19 00:24 UTC, merged